service: DBStartStopFunction

# plugins:
#   - serverless-python-requirements

# custom:
#   pythonRequirements:
#     zip: true

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-southeast-1
  iam:
    role: arn:aws:iam::940734073892:role/DBStartStopAutomateRole

package:
  individually: true

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true

functions:
  shut_rds_all:
    handler: handler.shut_rds_all
    description: Auto off db lambda function
    events:
      - schedule: cron(0 8 * * ? *)
      - schedule: cron(10 8 * * ? *)

    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"

    environment:
      KEY: "${ssm:/DB_Start_Stop/dev/lambda/KEY}"
      REGION: "${ssm:/DB_Start_Stop/dev/lambda/REGION}"
      VALUE: "${ssm:/DB_Start_Stop/dev/lambda/VALUE}"

  start_rds_all:
    handler: handler.start_rds_all
    description: Auto start db lambda function
    events:
      - schedule: cron(45 8 * * ? *)
      - schedule: cron(55 8 * * ? *)
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
    environment:
      KEY: "${ssm:/DB_Start_Stop/dev/lambda/KEY}"
      REGION: "${ssm:/DB_Start_Stop/dev/lambda/REGION}"
      VALUE: "${ssm:/DB_Start_Stop/dev/lambda/VALUE}"
